# -*- coding: utf-8 -*-
"""Image_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDZHs9LPSIt2Nbv1DmPGCLKaql6wfScT
"""

#### Transformers

from PIL import Image
from matplotlib import pyplot as plt
image=Image.open("/content/cat.1.jpg")
plt.imshow(image)

from transformers import pipeline

image_classifier=pipeline(task="image-classification")

image_classifier(image)

vqa=pipeline(task="vqa")

vqa(image=image,question="How many eyes are there?")

import requests

# Sample image URL
image_url = "https://huggingface.co/datasets/mishig/sample_images/resolve/main/tiger.jpg"
image = Image.open(requests.get(image_url, stream=True).raw)

classifier = pipeline("image-classification", model="google/vit-base-patch16-224")
print(classifier(image))

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("image-classification", model="google/vit-base-patch16-224")
pipe("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/hub/parrots.png")

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("visual-question-answering", model="Salesforce/blip-vqa-capfilt-large")

### Image to text

from transformers import pipeline

pipe = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")
from PIL import Image
import matplotlib.pyplot as plt
import requests # Import the requests library

# Load the image directly from the URL
image_url = "https://wallup.net/wp-content/uploads/2016/04/06/345186-forest-winter-snow-landscape-pine_trees.jpg"  # Replace with your desired image URL
image = Image.open(requests.get(image_url, stream=True).raw)
pipe(image)

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("image-to-text", model="rookiemistakes/swin_hindi_llm_small_img_capt")

image_url = "https://wallup.net/wp-content/uploads/2016/04/06/345186-forest-winter-snow-landscape-pine_trees.jpg"  # Replace with your desired image URL
image = Image.open(requests.get(image_url, stream=True).raw)
pipe(image)

Build a Gradio app with 3 tabs:

Visual Question Answering (VQA)

Image Classification

Image Captioning

Each tab should support image input via upload, camera, and URL.
The assessment tests ' skills in prompting, debugging, and deploying a multi-modal interface

